### ISSUE TITLE
Missing LICENSE and CONTRIBUTING docs

### ISSUE THREAD

**Issue by bdunn313** [adammpkins/bumblefuck#1]
How do I know what I can steal and/or how to share back things I pirated and hacked on? :-P

**Comment by adammpkins** [comment]
@bdunn313 Just for you. [0ab95b28b8c08661521df19f54d602761e1a928a](https://github.com/adammpkins/bumblefuck/commit/0ab95b28b8c08661521df19f54d602761e1a928a)

**Comment by adammpkins** [comment]
@bdunn313 Just for you. [✅added docs for Brad](https://github.com/adammpkins/bumblefuck/commit/0ab95b28b8c08661521df19f54d602761e1a928a)
